spring:
  profiles:
    active: "prod"
  resources:
    static-locations: classpath:/static/

server:
  port: 8088
  servlet:
    context-path: /

---
spring:
  profiles: dev
  security:
    require-ssl: true

settings:
  openvpnKeysPath: '/home/user/devel/java/tmp/'
  openvpnConfigPath: './conf/'
  openVpnBinary: '/usr/sbin/openvpn'

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

server:
  ssl:
    key-store: "classpath:keystore/localhost.jks"
    key-store-password: "1234567890"
    keyStoreType: "JKS"
    trust-store: 'classpath:keystore/keystore.jks'
    trust-store-password: '1234567890'

---
spring:
  profiles: prod

settings:
  openvpnKeysPath: '/openvpn/data'
  openvpnConfigPath: '/openvpn/data'
  openVpnBinary: '/usr/sbin/openvpn'

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
